name: sprawozdanie.yml
on: push
jobs: 
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - run: pip install ipykernel scipy pint numpy matplotlib open_atmos_jupyter_utils PyMPDATA
      - uses: actions/checkout@v4
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - run: pip install nbconvert
      - run: python -m nbconvert --to pdf --no-input --execute projekt-shallow_water_v2.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: projekt-shallow_water.pdf