name: sprawozdanie.yml
on: push
jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: pip install ipykernel scipy pint open_atmos_jupyter_utils numpy PyMPDATA
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - run: pip install nbconvert
      - run: jupyter nbconvert --to latex --no-input --execute projekt-shallow_water.ipynb
      - run: sed -i '/HBox(children=/d' PROJEKT.tex
      - run: xelatex -interaction=nonstopmode PROJEKT.tex
      - uses: actions/upload-artifact@v4
        with:
          name: projekt-shallow_water.pdf
          path: projekt-shallow_water.pdf